# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Ot_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ot_fieldtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ot_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ot_fields',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ot_webservice_api.Ot_object'),
        ),
        migrations.AddField(
            model_name='ot_fields',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ot_webservice_api.Ot_fieldtypes'),
        ),
    ]
