# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_webservice_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='Ot_config',
        ),
        migrations.RenameModel(
            old_name='Ot_fields',
            new_name='Ot_field',
        ),
        migrations.RenameModel(
            old_name='Ot_fieldtypes',
            new_name='Ot_fieldtype',
        ),
        migrations.AddField(
            model_name='ot_object',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
