# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_webservice_api', '0002_auto_20171030_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot_config',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
