# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ot_webservice_api', '0005_auto_20171109_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='wnd',
            new_name='end',
        ),
    ]
