# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_webservice_api', '0008_auto_20171109_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='call',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ucid',
        ),
        migrations.AlterField(
            model_name='call',
            name='ucid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
