# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_webservice_api', '0009_auto_20171109_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ucid',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
