# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ot_webservice_api', '0012_call_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_applicant', to='ot_webservice_api.Agent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='destination',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_responsible', to='ot_webservice_api.Agent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ot_webservice_api.Ticket'),
        ),
    ]
