# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_webservice_api', '0013_auto_20171109_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
